image: gradle:jdk14

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x gradlew

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .gradle/
    - build/

build:
  stage: build
  script:
    - ./gradlew --build-cache assemble

test:
  stage: test
  script:
    - ./gradlew check